// Generated by generate.py. Do not edit manually.
export default [
  {
    "label": "Главная",
    "slug": "index"
  },
  {
    "label": "ЧаВо",
    "slug": "faq"
  },
  {
    "label": "Команды",
    "slug": "commands"
  },
  {
    "label": "Серверные крафты",
    "slug": "recipes"
  },
  {
    "label": "Напитки",
    "items": [
      {
        "label": "Обзор",
        "slug": "drinks"
      },
      {
        "label": "Чаи",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/teas"
          },
          {
            "label": "Зелёный чай",
            "slug": "drinks/teas/green_tea"
          },
          {
            "label": "Чай из папоротника",
            "slug": "drinks/teas/fern_tea"
          },
          {
            "label": "Цветочный чай",
            "slug": "drinks/teas/flower_tea"
          },
          {
            "label": "Мятный чай",
            "slug": "drinks/teas/mint_tea"
          },
          {
            "label": "Розовый чай",
            "slug": "drinks/teas/rose_tea"
          },
          {
            "label": "Сиреневый чай",
            "slug": "drinks/teas/lilac_tea"
          },
          {
            "label": "Чай из азалии",
            "slug": "drinks/teas/azalea_tea"
          },
          {
            "label": "Ягодный чай",
            "slug": "drinks/teas/berry_tea"
          },
          {
            "label": "Какао-чай",
            "slug": "drinks/teas/cocoa_tea"
          }
        ]
      },
      {
        "label": "Соки и морсы",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/juices"
          },
          {
            "label": "Яблочный сок",
            "slug": "drinks/juices/apple_juice"
          },
          {
            "label": "Морковный сок",
            "slug": "drinks/juices/carrot_juice"
          },
          {
            "label": "Арбузный сок",
            "slug": "drinks/juices/melon_juice"
          },
          {
            "label": "Тыквенный сок",
            "slug": "drinks/juices/pumpkin_juice"
          },
          {
            "label": "Свекольный сок",
            "slug": "drinks/juices/beet_juice"
          },
          {
            "label": "Ягодный морс",
            "slug": "drinks/juices/berry_mors"
          },
          {
            "label": "Глоу-морс",
            "slug": "drinks/juices/glow_mors"
          },
          {
            "label": "Кактусовый фреш",
            "slug": "drinks/juices/cactus_fresh"
          },
          {
            "label": "Компот",
            "slug": "drinks/juices/compote"
          }
        ]
      },
      {
        "label": "Квасы",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/kvass"
          },
          {
            "label": "Хлебный квас",
            "slug": "drinks/kvass/bread_kvass"
          },
          {
            "label": "Свекольный квас",
            "slug": "drinks/kvass/beet_kvass"
          },
          {
            "label": "Берёзовый квас",
            "slug": "drinks/kvass/birch_kvass"
          },
          {
            "label": "Медовый квас",
            "slug": "drinks/kvass/honey_kvass"
          }
        ]
      },
      {
        "label": "Молочные и согревающие",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/milk"
          },
          {
            "label": "Молоко с мёдом",
            "slug": "drinks/milk/milk_honey"
          },
          {
            "label": "Какао на молоке",
            "slug": "drinks/milk/cocoa_milk"
          },
          {
            "label": "Топлёное молоко",
            "slug": "drinks/milk/baked_milk"
          },
          {
            "label": "Ягодный молочный коктейль",
            "slug": "drinks/milk/berry_milkshake"
          },
          {
            "label": "Тыквенный латте",
            "slug": "drinks/milk/pumpkin_latte"
          }
        ]
      },
      {
        "label": "Прохладительные",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/cold"
          },
          {
            "label": "Лимонад",
            "slug": "drinks/cold/lemonade"
          },
          {
            "label": "Мятный лимонад",
            "slug": "drinks/cold/mint_lemonade"
          },
          {
            "label": "Ягодный смузи",
            "slug": "drinks/cold/berry_smoothie"
          },
          {
            "label": "Арбузный айс",
            "slug": "drinks/cold/melon_ice"
          },
          {
            "label": "Холодный чай",
            "slug": "drinks/cold/iced_tea"
          },
          {
            "label": "Глоу-лимонад",
            "slug": "drinks/cold/glow_lemonade"
          }
        ]
      },
      {
        "label": "Отвары",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/brews"
          },
          {
            "label": "Грибной отвар",
            "slug": "drinks/brews/mushroom_broth"
          },
          {
            "label": "Настой пустоши",
            "slug": "drinks/brews/wasteland_brew"
          },
          {
            "label": "Маковый настой",
            "slug": "drinks/brews/poppy_brew"
          },
          {
            "label": "Отвар ламинарии",
            "slug": "drinks/brews/kelp_broth"
          },
          {
            "label": "Эликсир одуванчиков",
            "slug": "drinks/brews/dandelion_elixir"
          },
          {
            "label": "Валерьянка",
            "slug": "drinks/brews/valerian"
          },
          {
            "label": "Кошачья мята",
            "slug": "drinks/brews/catnip"
          },
          {
            "label": "Сбитень",
            "slug": "drinks/brews/sbiten"
          }
        ]
      },
      {
        "label": "Коктейли (моктейли)",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/cocktails"
          },
          {
            "label": "Малиновый закат",
            "slug": "drinks/cocktails/raspberry_sunset"
          },
          {
            "label": "Тропический бриз",
            "slug": "drinks/cocktails/tropical_breeze"
          },
          {
            "label": "Мохито без алкоголя",
            "slug": "drinks/cocktails/mojito"
          },
          {
            "label": "Пина колада",
            "slug": "drinks/cocktails/pina_colada"
          },
          {
            "label": "Кровавая Мэри",
            "slug": "drinks/cocktails/bloody_mary"
          },
          {
            "label": "Цитрусовый взрыв",
            "slug": "drinks/cocktails/citrus_burst"
          },
          {
            "label": "Ягодный дайкири",
            "slug": "drinks/cocktails/berry_daiquiri"
          },
          {
            "label": "Шоколадный гром",
            "slug": "drinks/cocktails/chocolate_thunder"
          },
          {
            "label": "Медовый физз",
            "slug": "drinks/cocktails/honey_fizz"
          },
          {
            "label": "Изумрудный сад",
            "slug": "drinks/cocktails/emerald_garden"
          },
          {
            "label": "Ночная Роса",
            "slug": "drinks/cocktails/night_dew"
          },
          {
            "label": "Фейерверк",
            "slug": "drinks/cocktails/fireworks"
          }
        ]
      },
      {
        "label": "Редкие эксклюзивы",
        "collapsed": true,
        "items": [
          {
            "label": "Обзор",
            "slug": "drinks/exclusive"
          },
          {
            "label": "Эликсир Кипрея",
            "slug": "drinks/exclusive/fireweed_elixir"
          },
          {
            "label": "Янтарный концентрат",
            "slug": "drinks/exclusive/amber_concentrate"
          },
          {
            "label": "Сердце Глубин",
            "slug": "drinks/exclusive/heart_of_depths"
          },
          {
            "label": "Золотое молоко",
            "slug": "drinks/exclusive/golden_milk"
          },
          {
            "label": "Адский настой",
            "slug": "drinks/exclusive/nether_brew"
          },
          {
            "label": "Шёпот Дриад",
            "slug": "drinks/exclusive/dryad_whisper"
          },
          {
            "label": "Слеза Края",
            "slug": "drinks/exclusive/end_tear"
          },
          {
            "label": "Эликсир Дракона",
            "slug": "drinks/exclusive/dragon_elixir"
          }
        ]
      }
    ]
  }
];
